#!/bin/bash -eE

# Fix bug #3 "glibc build loop in NPTL"
mkdir -p ./$PREFIX/include
if [ -d $PREFIX/libc-include ]; then
	cp -a $PREFIX/libc-include/* ./$PREFIX/include
	rm -rf $PREFIX/libc-include
fi

# Install NIS and RPC related headers that are not installed by default; these are required by several BLFS packages.
cp -v $SRC_DIR/sunrpc/rpc/*.h ./$PREFIX/include/rpc
cp -v $SRC_DIR/sunrpc/rpcsvc/*.h ./$PREFIX/include/rpcsvc
cp -v $SRC_DIR/nis/rpcsvc/*.h ./$PREFIX/include/rpcsvc

# Individual locales can be installed using the localedef program. E.g., the first localedef command below combines the /usr/share/i18n/locales/cs_CZ charset-independent locale definition with the /usr/share/i18n/charmaps/UTF-8.gz charmap definition and appends the result to the /usr/lib/locale/locale-archive file.
if [ $LOCALES != all ]; then
    mkdir -pv ./$PREFIX/lib/locale
    for LOCALE in $LOCALES; do
	case $LOCALE in
	    en_HK|en_PH|en_US|es_MX|fr_FR|it_IT)
		./$PREFIX/bin/localedef -i $LOCALE -f ISO-8859-1 $LOCALE --prefix=./
		;;&
	    zh_CN|cs_CZ|de_DE|en_US|fr_FR|tr_TR)
		./$PREFIX/bin/localedef -i $LOCALE -f UTF-8 $LOCALE.UTF-8 --prefix=./
		;;&
	    de_DE|fr_FR)
		./$PREFIX/bin/localedef -i $LOCALE@euro -f ISO-8859-15 $LOCALE@euro --prefix=./
		;;&
	    fa_IR)
		./$PREFIX/bin/localedef -i $LOCALE -f UTF-8 $LOCALE --prefix=./
		;;
	    zh_CN)
		./$PREFIX/bin/localedef -i $LOCALE -f GB18030 $LOCALE.GB18030 --prefix=./
		;;
	    ja_JP)
		./$PREFIX/bin/localedef -i $LOCALE -f EUC-JP $LOCALE --prefix=./
		;;
	esac
    done
else
    # Alternatively, install all locales listed in the glibc-2.15/localedata/SUPPORTED file.
    pushd $MAKEDIR
    make DESTDIR=$(dirs -l +1) localedata/install-locales
    popd
fi

# The /etc/nsswitch.conf file needs to be created because, although Glibc provides defaults when this file is missing or corrupt, the Glibc defaults do not work well in a networked environment. The time zone also needs to be configured. 
mkdir -pv etc
cat > etc/nsswitch.conf << "EOF"
# Begin /etc/nsswitch.conf

passwd: files
group: files
shadow: files

hosts: files dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

# End /etc/nsswitch.conf
EOF

mkdir -pv $PREFIX/share/zoneinfo/{posix,right}
for tz in etcetera southamerica northamerica europe africa antarctica asia australasia backward pacificnew solar87 solar88 solar89 systemv; do
	zic -L /dev/null -d ./$PREFIX/share/zoneinfo -y "sh yearistype.sh" $SRC_DIR/${tz}
	zic -L /dev/null -d ./$PREFIX/share/zoneinfo/posix -y "sh yearistype.sh" $SRC_DIR/${tz}
	zic -L $SRC_DIR/leapseconds -d ./$PREFIX/share/zoneinfo -y "sh yearistype.sh" $SRC_DIR/${tz}
done
cp -v $SRC_DIR/zone.tab .$PREFIX/share/zoneinfo
zic -d ./$PREFIX/share/zoneinfo -p Asia/Shanghai
cp -v --remove-destination ./$PREFIX/share/zoneinfo/Asia/Shanghai etc/localtime

# By default, the dynamic loader (/lib/ld-linux.so.2) searches through /lib and /usr/lib for dynamic libraries that are needed by programs as they are run. However, if there are libraries in directories other than /lib and /usr/lib, these need to be added to the /etc/ld.so.conf file in order for the dynamic loader to find them. Two directories that are commonly known to contain additional libraries are /usr/local/lib and /opt/lib, so add those directories to the dynamic loader's search path. 
cat > etc/ld.so.conf << "EOF"
# Begin /etc/ld.so.conf
/usr/local/lib
/opt/lib
# Add an include directory
include /etc/ld.so.conf.d/*.conf
EOF
