#!/bin/sh
#[ -h /usr/lib/rpm ] && rm -v /usr/lib/rpm
cp -a $PKG_DIR/BUILDROOT/usr/include /usr/kernel-headers
cp -av $MAKEDIR/$PKG_NAME-$VERSION/drivers/staging/cdv/imgv/*.h ./$PREFIX/include
cp -av $MAKEDIR/$PKG_NAME-$VERSION/include/drm/ttm ./$PREFIX/include

mkdir -pv boot/grub
cat > boot/grub/grub.cfg << EOF
# Begin /boot/grub/grub.cfg
set default=0
set timeout=3

insmod ext2
set root=(hd0,1)

menuentry "GNU/Linux, Linux ${VERSION}${KERN_SUFFIX}" {
        linux   /boot/vmlinuz-${VERSION}${KERN_SUFFIX} root=/dev/sda1 ro
}
EOF
