#!/bin/sh

# Move programs to the locations specified by the FHS.
mv -v usr/bin/{cat,chgrp,chmod,chown,cp,date,dd,df,echo} bin
mv -v usr/bin/{false,ln,ls,mkdir,mknod,mv,pwd,rm} bin
mv -v usr/bin/{rmdir,stty,sync,true,uname} bin
mv -v usr/bin/chroot usr/sbin
mv -v usr/share/man/man1/chroot.1 usr/share/man/man8/chroot.8
sed -i s/\"1\"/\"8\"/1 usr/share/man/man8/chroot.8

# Some of the scripts in the bootscripts depend on head, sleep, and nice. As /usr may not be available during the early stages of booting, those binaries need to be on the root partition.
mv -v usr/bin/{head,sleep,nice} bin
