#!/bin/bash

if [ "$EUID" != 0 ]; then
	echo "You have to be root to run \"$0\"" >&2
	exec su -c $0 $@
fi

SDK_FS="buildsys.ext4"
# Set fs size to 2G
SDK_FS_SIZE=$((2*1024*1024*1024))
SDK_URL="ftp://w1ball.3322.org:2102/${SDK_FS}.xz"

if [ -z "$1" ]; then
	DEVROOT="$(pwd)"
else
	DEVROOT="$1"
fi
SDE="${DEVROOT}/SDE"
[ -d "$SDE" ] || mkdir "$SDE"

quit()
{
	set +e
	DIRS=$(dirs -l -p | sed '1d')
	for DIR in $DIRS; do
		umount -lv $DIR
	done
}

trap quit EXIT
set -e
dirs -c

cd "$DEVROOT"
if [ ! -r ${SDK_FS} ]; then
	if [ ! -r ${SDK_FS}.xz ]; then
		wget "${SDK_URL}"
	fi
	xz -dv ${SDK_FS}.xz
fi
if (( $(stat -c%s ${SDK_FS}) < ${SDK_FS_SIZE} )); then
	e2fsck -f ${SDK_FS}
	resize2fs ${SDK_FS} $((${SDK_FS_SIZE}/1024))K
fi
mount -vo loop -t ext4 "$DEVROOT/${SDK_FS}" "$SDE"
pushd -n "$SDE" &> /dev/null
mount -v --bind /dev "$SDE/dev"
pushd -n "$SDE/dev" &> /dev/null
mount -vt devpts devpts "$SDE/dev/pts"
pushd -n "$SDE/dev/pts" &> /dev/null
mount -vt tmpfs shm "$SDE/dev/shm"
pushd -n "/run/shm" &> /dev/null
mount -vt proc proc "$SDE/proc"
pushd -n "$SDE/proc" &> /dev/null
mount -vt sysfs sysfs "$SDE/sys"
pushd -n "$SDE/sys" &> /dev/null
mount -v --bind "$DEVROOT" "$SDE/root"
pushd -n "$SDE/root" &> /dev/null
linux32 /usr/sbin/chroot "$SDE" /tools/bin/env -i \
    HOME=/root TERM="$TERM" PS1='\u:\w\$ ' \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin \
    /tools/bin/bash --login +h
