#!/bin/bash

PATH=$PATH:/sbin:/usr/sbin
[ -z "$SDK_FS" ] && SDK_FS="buildsys-i686.ext4"
# Set default fs size to 1G
SDK_FS_SIZE=$((1*1024*1024*1024))
SDK_URL="ftp://w1ball.3322.org:2102/buildsys/${SDK_FS}.xz"
[ "$(uname -m)" = x86_64 ] && SET32=linux32

print_help_and_exit()
{
	exec >&2
	echo -e "Usage:\n $(basename $0) [Options] [DevRootDir]"
	echo "Options:"
	echo " --i686		Enter SDK environment for i686 architecture (default)"
	echo " --arm		Enter SDK environment for ARM architecture"
	echo " -h, --help	Print this help"
	echo "DevRootDir:"
	echo " \"package name\"	The root directory for development, default is current directory"
	exit
}

quit()
{
	set +e
	DIRS=$(dirs -l -p | sed '1d')
	for DIR in $DIRS; do
		if ! umount -v $DIR; then
			umount -v -l $DIR
		fi
	done
}

GETOPTS=$(getopt -o h --long arm,i686,help -n "$0" -- "$@")
[ $? != 0 ] && print_help_and_exit

eval set -- "$GETOPTS"
while true; do
	case "$1" in
		--arm)
			export SDK_FS=buildsys-arm.ext4; shift
			;;
		--i686)
			export SDK_FS=buildsys-i686.ext4; shift
			;;
		-h | --help)
			print_help_and_exit; shift
			;;
		--)
			shift ; break
			;;
		*)
			print_help_and_exit
			;;
	esac
done

if [ "$EUID" != 0 ]; then
	echo "You have to be root to run \"$0\"" >&2
	exec su -c $0 $@
fi

trap quit EXIT
set -e

if [ -z "$1" ]; then
	DEVROOT="$(pwd)"
else
	DEVROOT="$1"
fi

SDE="${DEVROOT}/SDE"
[ -d "$SDE" ] || mkdir "$SDE"

cd "$DEVROOT"
if [ ! -r ${SDK_FS} ]; then
	if [ ! -r ${SDK_FS}.xz ]; then
		mkdir -pv partial
		wget -P partial -c "${SDK_URL}"
		mv partial/${SDK_FS}.xz .
	fi
	xz -dv ${SDK_FS}.xz
fi
if (( $(stat -c%s ${SDK_FS}) < ${SDK_FS_SIZE} )); then
	e2fsck -f ${SDK_FS}
	resize2fs ${SDK_FS} $((${SDK_FS_SIZE}/1024))K
fi
dirs -c
mount -vo loop -t ext4 "$DEVROOT/${SDK_FS}" "$SDE"
pushd -n "$SDE" &> /dev/null
mount -v --bind /dev "$SDE/dev"
pushd -n "$SDE/dev" &> /dev/null
mount -vt devpts devpts "$SDE/dev/pts"
pushd -n "$SDE/dev/pts" &> /dev/null
mount -vt tmpfs shm "$SDE/dev/shm"
pushd -n "/run/shm" &> /dev/null
mount -vt proc proc "$SDE/proc"
pushd -n "$SDE/proc" &> /dev/null
mount -vt sysfs sysfs "$SDE/sys"
pushd -n "$SDE/sys" &> /dev/null
mount -v --bind "$DEVROOT" "$SDE/root"
pushd -n "$SDE/root" &> /dev/null
$SET32 /usr/sbin/chroot "$SDE" /tools/bin/env -i \
    HOME=/root TERM="$TERM" PS1='\u:\w\$ ' \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin \
    /tools/bin/bash --login +h
