#!/bin/bash

if [ "$EUID" != 0 ]; then
	echo "You have to be root to run $0"
	exit 1
fi

if [ -z "$1" ]; then
	DEVROOT="$(pwd)"
else
	DEVROOT="$1"
fi
SDE="${DEVROOT}/SDE"
[ -d "$SDE" ] || mkdir "$SDE"

quit()
{
	set +e
	DIRS=$(dirs -l -p | sed '1d')
	for DIR in $DIRS; do
		umount -v $DIR
	done
}

trap quit EXIT

set -e
dirs -c
mount -vo loop -t ext4 "$DEVROOT/buildsys.ext4" "$SDE"
pushd -n "$SDE" &> /dev/null
mount -v --bind /dev "$SDE/dev"
pushd -n "$SDE/dev" &> /dev/null
mount -vt devpts devpts "$SDE/dev/pts"
pushd -n "$SDE/dev/pts" &> /dev/null
mount -vt tmpfs shm "$SDE/dev/shm"
pushd -n "$SDE/dev/shm" &> /dev/null
mount -vt proc proc "$SDE/proc"
pushd -n "$SDE/proc" &> /dev/null
mount -vt sysfs sysfs "$SDE/sys"
pushd -n "$SDE/sys" &> /dev/null
mount -v --bind "$DEVROOT" "$SDE/root"
pushd -n "$SDE/root" &> /dev/null
#linux32 chroot "$SDE" su - lfs
linux32 /usr/sbin/chroot "$SDE" /tools/bin/env -i \
    HOME=/root TERM="$TERM" PS1='\u:\w\$ ' \
    PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin \
    /tools/bin/bash --login +h
