#!/bin/sh

[ "$PWD" = '/' ] && exit

install -d ./isolinux
install $SRC_DIR/core/isolinux.bin ./isolinux
mv -v boot/* ./isolinux
rmdir -v boot
ln -vsf isolinux boot
pushd isolinux
for KERN_FILE in vmlinuz System.map config; do
    mv ${KERN_FILE}-3.4.3-buildsys-cd $KERN_FILE
done
rm *-buildsys
popd

cat > isolinux/isolinux.cfg <<- "EOF"
default bootcd
prompt 1
timeout 40

label bootcd
kernel vmlinuz
append initrd=initrd.gz root=/dev/ram0 init=/linuxrc ramdisk_size=16384

label initrdshell
kernel vmlinuz
append initrd=initrd.gz root=/dev/ram0 init=/bin/bash ramdisk_size=16384
EOF
