#!/bin/sh -eET

[ "$PWD" = '/' ] && exit

install -d ./isolinux
install $SRC_DIR/core/isolinux.bin ./isolinux
cp -av boot/* ./isolinux
pushd isolinux
for KERN_FILE in vmlinuz System.map config; do
    mv -fv $KERN_FILE* $KERN_FILE
done
rm -vf *-buildsys
popd
rm -vfr boot
ln -vsf isolinux boot

cat > isolinux/isolinux.cfg <<- "EOF"
default bootcd
prompt 1
timeout 40

label bootcd
kernel vmlinuz
append initrd=initrd.gz root=/dev/ram0 init=/linuxrc ramdisk_size=16384

label initrdshell
kernel vmlinuz
append initrd=initrd.gz root=/dev/ram0 init=/bin/bash ramdisk_size=16384
EOF
