#!/bin/bash -eE

cp -v ${MAKEDIR}/bzip2-shared bin/bzip2
cp -av ${MAKEDIR}/libbz2.so* lib
#ln -sv ../../lib/libbz2.so.1.0 /usr/lib/libbz2.so
rm -v usr/bin/{bunzip2,bzcat,bzip2}
ln -sfv bzip2 bin/bunzip2
ln -sfv bzip2 bin/bzcat
