#!/bin/sh

# Some of the scripts in the LFS-Bootscripts package depend on kbd_mode, loadkeys, openvt, and setfont. As /usr may not be available during the early stages of booting, those binaries need to be on the root partition:
mv -v usr/bin/{kbd_mode,loadkeys,openvt,setfont} bin
