#!/bin/bash -eE

mkdir -pv bin lib ./$PREFIX/bin
cp -v ${MAKEDIR}/bzip2-shared bin/bzip2
cp -av ${MAKEDIR}/libbz2.so* lib
#ln -sv ../../lib/libbz2.so.1.0 /$PREFIX/lib/libbz2.so
rm -vf ./$PREFIX/bin/{bunzip2,bzcat,bzip2}
ln -sfv bzip2 bin/bunzip2
ln -sfv bzip2 bin/bzcat
mv -vf ./$PREFIX/bin/bz{cmp,diff,egrep,fgrep,grep,less,more,ip2recover} bin
