#!/bin/bash -eE

if [ $PREFIX = /tools ]; then
	SYSROOT=/tools
fi

for target in depmod insmod modinfo modprobe rmmod; do
	ln -sfv ../bin/kmod .$SYSROOT/sbin/$target
done

ln -sfv kmod .$SYSROOT/bin/lsmod
