#!/bin/sh

# Some packages expect the C preprocessor to be installed in the /lib directory.
ln -sv ../usr/bin/cpp lib

# Many packages use the name cc to call the C compiler.
ln -sv gcc usr/bin/cc

# Move a misplced file
GDBDIR=usr/share/gdb/auto-load/usr/lib/gcc/i686-pc-linux-gnu/4.6.3
mkdir -pv $GDBDIR
mv -v usr/lib/*gdb.py $GDBDIR
unset GDBDIR
