#!/bin/sh

DESTDIR=${PWD}
cd $SRC_DIR/mozilla/dist
install -v -m755 Linux*/lib/*.so $DESTDIR/usr/lib
install -v -m644 Linux*/lib/{*.chk,libcrmf.a} $DESTDIR/usr/lib
install -v -m755 -d $DESTDIR/usr/include/nss
cp -v -RL {public,private}/nss/* $DESTDIR/usr/include/nss
chmod 644 $DESTDIR/usr/include/nss/*
install -v -m755 Linux*/bin/{certutil,nss-config,pk12util} $DESTDIR/usr/bin
install -v -m644 Linux*/lib/pkgconfig/nss.pc $DESTDIR/usr/lib/pkgconfig
