#!/bin/sh

DESTDIR=${PWD}
cd $SRC_DIR/mozilla/dist
install -v -m755 Linux*/lib/*.so $DESTDIR/$PREFIX/lib
install -v -m644 Linux*/lib/{*.chk,libcrmf.a} $DESTDIR/$PREFIX/lib
install -v -m755 -d $DESTDIR/$PREFIX/include/nss
cp -v -RL {public,private}/nss/* $DESTDIR/$PREFIX/include/nss
chmod 644 $DESTDIR/$PREFIX/include/nss/*
install -v -m755 Linux*/bin/{certutil,nss-config,pk12util} $DESTDIR/$PREFIX/bin
install -v -m644 Linux*/lib/pkgconfig/nss.pc $DESTDIR/$PREFIX/lib/pkgconfig
