#!/bin/sh

mkdir -pv boot/grub

cat > boot/grub/grub.cfg << "EOF"
# Begin /boot/grub/grub.cfg
set default=0
set timeout=3

insmod ext2
set root=(hd0,1)

menuentry "GNU/Linux, Linux 3.4.3-buildsys" {
        linux   /boot/vmlinuz-3.4.3-buildsys root=/dev/sda1 ro
}
EOF
