#!/bin/sh

# Install the modules, if the kernel configuration uses them:
pushd "$MAKEDIR"
make DESTDIR=$(dirs +1) modules_install
popd
# The path to the kernel image may vary depending on the platform being used. The filename below can be changed to suit your taste, but the stem of the filename should be vmlinuz to be compatible with the automatic setup of the boot process described in the next section. The following command assumes an x86 architecture:
cp -v arch/x86/boot/bzImage boot/vmlinuz-3.3.5
# System.map is a symbol file for the kernel. It maps the function entry points of every function in the kernel API, as well as the addresses of the kernel data structures for the running kernel. It is used as a resource when investigating kernel problems. Issue the following command to install the map file:
cp -v System.map boot/System.map-3.3.5
# The kernel configuration file .config produced by the make menuconfig contains all the configuration selections for the kernel that was just compiled. It is a good idea to keep this file for future reference:
cp -v .config boot/config-3.3.5

# The /etc/modprobe.d/usb.conf file needs to be created so that if the USB drivers (ehci_hcd, ohci_hcd and uhci_hcd) have been built as modules, they will be loaded in the correct order; ehci_hcd needs to be loaded prior to ohci_hcd and uhci_hcd in order to avoid a warning being output at boot time.
install -v -m755 -d etc/modprobe.d
cat > etc/modprobe.d/usb.conf << "EOF"
# Begin /etc/modprobe.d/usb.conf

install ohci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i ohci_hcd ; true
install uhci_hcd /sbin/modprobe ehci_hcd ; /sbin/modprobe -i uhci_hcd ; true

# End /etc/modprobe.d/usb.conf
EOF
