#!/bin/sh

# When run-levels are changed (for example, when halting the system), init sends termination signals to those processes that init itself started and that should not be running in the new run-level. While doing this, init outputs messages like “Sending processes the TERM signal” which seem to imply that it is sending these signals to all currently running processes. To avoid this misinterpretation, modify the source so that these messages read like “Sending processes configured via /etc/inittab the TERM signal” instead:
sed -i 's@Sending processes@& configured via /etc/inittab@g' src/init.c

# Maintained versions of the wall and mountpoint programs were installed earlier by Util-linux. Suppress the installation of Sysvinit's versions of these programs and their man pages:
sed -i -e 's/utmpdump wall/utmpdump/' \
	-e '/= mountpoint/d' \
	-e 's/mountpoint.1 wall.1//' src/Makefile
