#!/bin/sh

chown -v -R root:root                        \
      ./$PREFIX/bin/db_*                          \
      ./$PREFIX/include/db{,_185,_cxx}.h          \
      ./$PREFIX/lib/libdb*.{so,la}                \
      ./$PREFIX/share/doc/db-$VERSION
