#!/bin/sh

if [ $PREFIX != /tools ]; then
	mv -vf ./$PREFIX/lib ./lib
fi

chmod -v 0755 lib/libattr.so.1.1.0
rm -vf lib/libattr.{a,la,so}
#sed -i 's@/lib@/usr/lib@' ./$PREFIX/lib/libattr.la
mkdir -pv ./$PREFIX/lib
ln -sfv ../../lib/libattr.so.1 ./$PREFIX/lib/libattr.so
ln -sfv ../../lib/libattr.so.1 $PREFIX/lib/libattr.so
