#!/bin/sh
sed -i -e 's/"db1"/& \&\& $name ne "nss_test1"/' scripts/test-installation.pl
sed -i 's|@BASH@|/bin/bash|' elf/ldd.bash.in
sed -i '195,213 s/PRIVATE_FUTEX/FUTEX_CLOCK_REALTIME/' nptl/sysdeps/unix/sysv/linux/x86_64/pthread_rwlock_timed{rd,wr}lock.S
#mkdir -p $PKG_DIR/.build
#echo "CFLAGS += -march=i686 -mtune=native -O3 -pipe" > $PKG_DIR/.build/configparms
